name: ERD Build
on:
  push:
    branches: [ "main" ]

jobs:
  build-erd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate ER Diagrams
        run: npx @liam-hq/cli erd build --input y --format postgres

    # - Next step: Deploy ERD `./dist` to your preferred hosting service for easy sharing and access.
